// Canonical error codes. Consumers should use these constants rather than
// inlining strings so grepability stays good.

export const ErrorCodes = {
  PROFILE_INVALID: 'PROFILE_INVALID',
  PROFILE_NOT_FOUND: 'PROFILE_NOT_FOUND',
  PROFILE_RESET_CONFIRMED: 'PROFILE_RESET_CONFIRMED',
  PROFILE_PASSPHRASE_MISMATCH: 'PROFILE_PASSPHRASE_MISMATCH',
  PROJECT_NAME_CONFLICT: 'PROJECT_NAME_CONFLICT',
  PROJECT_NOT_FOUND: 'PROJECT_NOT_FOUND',
  PROJECT_LOCK_ACTIVE: 'PROJECT_LOCK_ACTIVE',
  PROJECT_READ_ONLY: 'PROJECT_READ_ONLY',
  PROJECT_INVALID_STATE: 'PROJECT_INVALID_STATE',
  IMPORT_TOO_MANY_FILES: 'IMPORT_TOO_MANY_FILES',
  IMPORT_SIZE_LIMIT_EXCEEDED: 'IMPORT_SIZE_LIMIT_EXCEEDED',
  IMPORT_UNSUPPORTED_TYPE: 'IMPORT_UNSUPPORTED_TYPE',
  IMPORT_EMPTY_FILENAME: 'IMPORT_EMPTY_FILENAME',
  IMPORT_ZERO_BYTES: 'IMPORT_ZERO_BYTES',
  IMPORT_BATCH_EMPTY: 'IMPORT_BATCH_EMPTY',
  MARKER_LIMIT_EXCEEDED: 'MARKER_LIMIT_EXCEEDED',
  MARKER_NOTE_REQUIRED: 'MARKER_NOTE_REQUIRED',
  MARKER_TIMESTAMP_OUT_OF_RANGE: 'MARKER_TIMESTAMP_OUT_OF_RANGE',
  FADE_RANGE_INVALID: 'FADE_RANGE_INVALID',
  BALANCE_RANGE_INVALID: 'BALANCE_RANGE_INVALID',
  EXPORT_CART_LIMIT_EXCEEDED: 'EXPORT_CART_LIMIT_EXCEEDED',
  EXPORT_INVALID_FORMAT: 'EXPORT_INVALID_FORMAT',
  EXPORT_INVALID_BITRATE: 'EXPORT_INVALID_BITRATE',
  EXPORT_INVALID_SAMPLE_RATE: 'EXPORT_INVALID_SAMPLE_RATE',
  PLAYLIST_LIMIT_EXCEEDED: 'PLAYLIST_LIMIT_EXCEEDED',
  QUIET_HOURS_DEFERRED: 'QUIET_HOURS_DEFERRED',
  JOB_STALLED_RECLAIMED: 'JOB_STALLED_RECLAIMED',
  JOB_RETRY_EXHAUSTED: 'JOB_RETRY_EXHAUSTED',
  QUOTA_EXCEEDED: 'QUOTA_EXCEEDED',
  CSV_ROW_INVALID: 'CSV_ROW_INVALID',
  ATTENDANCE_THRESHOLD_INVALID: 'ATTENDANCE_THRESHOLD_INVALID',
  ATTENDANCE_TOP_N_INVALID: 'ATTENDANCE_TOP_N_INVALID',
  COHORT_DATE_WINDOW_INVALID: 'COHORT_DATE_WINDOW_INVALID',
  COHORT_CANONICAL_ID_CONFLICT: 'COHORT_CANONICAL_ID_CONFLICT',
  STORAGE_UNAVAILABLE: 'STORAGE_UNAVAILABLE'
} as const;

export type ErrorCode = (typeof ErrorCodes)[keyof typeof ErrorCodes];

export function fail<T = never>(
  code: ErrorCode | string,
  message: string,
  details?: unknown
): { ok: false; code: string; message: string; details?: unknown } {
  return { ok: false, code, message, details };
}

export function ok<T>(data: T, warnings?: string[]): { ok: true; data: T; warnings?: string[] } {
  return warnings && warnings.length ? { ok: true, data, warnings } : { ok: true, data };
}
